# Copyright 2026 Daitum
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Module that defines various field types and configurations for working with tables in a model.

This module includes classes that represent different types of fields within a table, such as:

- `Field`: The basic field representing a column in a table, including its `id`, associated
    `id`, and `data_type`. Fields support validators for data validation with custom error
    messages and severity levels.
- `CalculatedField`: A field where the value is calculated based on the provided formula.
- `DataField`: A field with a predefined value, where the value is typically imported and may have
    an associated `default_value`.
- `ComboField`: A field that behaves like either a `CalculatedField` or a `DataField`.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING, Any

from typeguard import typechecked

from ._buildable import Buildable, json_type_info
from .data_types import MapDataType, ObjectDataType, _FieldBase
from .enums import SEVERITY_RANK, DataType, Severity
from .formula import Formula, Operand

if TYPE_CHECKING:
    from .tables import Table
    from .validator import Validator


@dataclass
@typechecked
class ValidationFieldsContainer:
    """
    Container for the calculated fields generated by a validator.

    Attributes:
        severity: The severity level of the associated validator.
        invalid_field: The calculated field that evaluates to True when the field is invalid.
        message_field: The calculated field that contains the error message when invalid.
        summary_message: Summary error message.
    """

    severity: Severity
    invalid_field: Field
    message_field: Field
    summary_message: str


# pylint: disable=too-many-instance-attributes
@typechecked
class Field(Buildable, _FieldBase, Operand):
    """
    Represents a field within a table, defining the field's id, associated table, data type, and
    optional order index.

    Fields can have validators attached to check field values and generate error messages when
    validation fails. Each field can have at most one validator per severity level.

    Attributes:
        id (str): The id of the field.
        id (str): The table to which the field belongs.
        data_type (DataType | model_generator.structures.ObjectDataType): The data type of the
            field.
        order_index (int, optional): The order index of the field within the table.
        description (str, optional): Description of the field.
    """

    def __init__(
        self,
        id: str,
        table: Table,
        data_type: DataType | ObjectDataType | MapDataType,
    ):
        """
        Initialize a Field.

        Args:
            id: The unique identifier of the field.
            table: The table to which the field belongs.
            data_type: The data type of the field (DataType, ObjectDataType, or MapDataType).
        """
        super().__init__(id)
        self.table_id = table.id
        self._table = table
        self.data_type = data_type
        self.order_index: int | None = None
        self.description: str | None = None
        self._tracking_group: str | None = None

        self._validators: list[Validator] = []
        self._combined_message_field: Field | None = None

    @property
    def table(self) -> Table:
        return self._table

    @property
    def tracking_group(self) -> str | None:
        return self._tracking_group

    @property
    def tracking_id(self) -> str:
        return "" if self._tracking_group is None else self._tracking_group + "_TRACKING_" + self.id

    def set_order_index(self, idx: int | None) -> Field:
        """Sets the order index of the field within the table. Returns self."""
        self.order_index = idx
        return self

    def set_description(self, desc: str | None) -> Field:
        """Sets the description of the field. Returns self."""
        self.description = desc
        return self

    def set_tracking_group(self, group: str | None) -> Field:
        """Sets the tracking group for this field. Returns self."""
        self._tracking_group = group
        return self

    def to_string(self) -> str:
        return f"[{self.id}]"

    def to_data_type(self) -> DataType | ObjectDataType | MapDataType:
        return self.data_type

    def add_validator(self, validator: Validator) -> None:
        """
        Attach a validator to this field.

        Each field can only have one validator per severity level.
        Attempting to add another validator with the same severity
        will raise a ValueError.

        Args:
            validator (Validator): The validator instance to attach.

        Raises:
            ValueError: If a validator with the same severity has
                already been added to this field.
        """

        if validator.severity in [val.severity for val in self._validators]:
            raise ValueError(f"Duplicate severity validator detected for field: {self.id}")

        self._validators.append(validator)
        validator._attach_to_field(self, self._table)  # pylint: disable=protected-access

    def get_validation_fields(
        self, severity: Severity | None = None
    ) -> list[ValidationFieldsContainer] | ValidationFieldsContainer | None:
        """
        Retrieve the validation fields associated with this field's validators.

        Args:
            severity: If provided, returns only the validation fields for that severity level.
                If None, returns validation fields for all attached validators.

        Returns:
            - A list of ``ValidationFieldsContainer`` if ``severity`` is None and validators exist.
            - A single ``ValidationFieldsContainer`` if a validator matching ``severity`` is found.
            - ``None`` if no validators are attached, or if no validator matches the given severity.
        """
        if not self._validators:
            return None

        # return all validations' fields in a list
        if not severity:
            validation_fields = []
            for validator in self._validators:
                validation_fields.append(
                    ValidationFieldsContainer(
                        validator.severity,
                        self._table.get_field(f"{self.id}__invalid__{validator.severity.value}"),
                        self._table.get_field(f"{self.id}__message__{validator.severity.value}"),
                        validator.summary_message,
                    )
                )

            return sorted(validation_fields, key=lambda v: SEVERITY_RANK.get(v.severity, 0))

        # return the corresponding validation fields
        for validator in self._validators:
            if validator.severity == severity:
                return ValidationFieldsContainer(
                    validator.severity,
                    self._table.get_field(f"{self.id}__invalid__{severity.value}"),
                    self._table.get_field(f"{self.id}__message__{severity.value}"),
                    validator.summary_message,
                )
        return None

    def get_combined_message_field(self) -> Field | None:
        """
        Returns a single calculated field that combines all per-severity message fields into one
        array, ordered from highest to lowest severity (CRITICAL → ERROR → WARNING → INFO).
        Blank messages are excluded from the array (``ignore_null=True``).

        The resulting field is registered on the table with the ID
        ``{id}__message__combined`` and cached so subsequent calls return the same field
        without rebuilding it.

        Returns:
            Field | None: The combined message calculated field, or ``None`` if this field has
            no validators.
        """
        # to avoid circular import
        from daitum_model import formulas  # pylint: disable=import-outside-toplevel

        if not self._validators:
            return None

        if self._combined_message_field is not None:
            return self._combined_message_field

        if len(self._validators) == 1:
            single_validator = self._validators[0]
            return self._table.get_field(f"{self.id}__message__{single_validator.severity.value}")

        # Sort highest severity first so the combined array is ordered
        sorted_validators = sorted(
            self._validators, key=lambda v: SEVERITY_RANK.get(v.severity, 0), reverse=True
        )
        msg_fields = [
            self._table.get_field(f"{self.id}__message__{v.severity.value}")
            for v in sorted_validators
        ]

        # ignore_null=True so blank messages are excluded from the array
        formula = formulas.ARRAY(True, *msg_fields)

        combined_id = f"{self.id}__message__combined"
        self._combined_message_field = self._table.add_calculated_field(combined_id, formula)
        return self._combined_message_field


@json_type_info("calculated")
@typechecked
class CalculatedField(Field):
    """
    Represents a calculated field within a table, including a formula and an optional source table.

    Attributes:
        formula (Formula): The formula used to calculate the field.

    Raises:
        ValueError: If the data type is `OBJECT` or `OBJECT_ARRAY` and no source table is provided.
    """

    def __init__(
        self,
        id: str,
        table: Table,
        formula: Formula,
    ):
        super().__init__(id, table, formula.data_type)
        self.formula = formula


@json_type_info("data")
@typechecked
class DataField(Field):
    """
    Represents a data field within a table, including attributes like default value and import
    format.

    Attributes:
        default_value (optional): The default value for the field.
        import_format (optional): The format in which the field is imported.
    """

    def __init__(
        self,
        id: str,
        table: Table,
        data_type: DataType | ObjectDataType | MapDataType,
    ):
        super().__init__(id, table, data_type)
        self.default_value: Any = None
        self.import_format: str | None = None
        self.unique: bool = False
        self.nullable: bool = False

    def set_default_value(self, value: Any) -> DataField:
        """Sets the default value for the field. Returns self."""
        self.default_value = value
        return self

    def set_import_format(self, fmt: str | None) -> DataField:
        """Sets the import format for the field. Returns self."""
        self.import_format = fmt
        return self

    def set_unique(self, unique: bool) -> DataField:
        """Sets whether the field value must be unique. Returns self."""
        self.unique = unique
        return self

    def set_nullable(self, nullable: bool) -> DataField:
        """Sets whether the field value may be null. Returns self."""
        self.nullable = nullable
        return self


@json_type_info("combo")
@typechecked
class ComboField(Field):
    """
    Represents a field within a table that can function like a `CalculatedField` but remains
    editable under specific conditions. The field is editable in the UI when the
    `calculate_in_optimiser` setting is `True`; otherwise, it is not editable. Essentially, when
    `calculate_in_optimiser` is `True`, the field behaves as a `DataField`, and when `False`,
    it functions as a `CalculatedField`.

    Attributes:
        formula (Formula): The formula used to calculate the value of this field.
        calculate_in_optimiser (bool): Indicates whether the field should be calculated during
        the optimisation process.
        import_format (optional[str]): The expected format of the field during data import,
        if applicable.
        order_index (optional[int]): The position of this field in the table order, if specified.
    """

    def __init__(
        self,
        id: str,
        table: Table,
        formula: Formula,
        calculate_in_optimiser: bool,
    ):
        super().__init__(id, table, formula.data_type)
        self.formula = formula
        self.calculate_in_optimiser = calculate_in_optimiser
        self.default_value: Any = None
        self.import_format: str | None = None

    def set_default_value(self, value: Any) -> ComboField:
        """Sets the default value for the field. Returns self."""
        self.default_value = value
        return self

    def set_import_format(self, fmt: str | None) -> ComboField:
        """Sets the import format for the field. Returns self."""
        self.import_format = fmt
        return self
