"""Generate the merged Formulas page, per-formula RST stubs, and the Operators reference.

The Sphinx reference is assembled from:

1. The hand-written intro at ``docs/daitum_model/formulas_intro.rst`` (the ``Formula`` class,
   ``CONST``, and a lead-in).
2. An autogenerated toctree listing every public formula function in
   :mod:`daitum_model.formulas`. Each function gets a stub at
   ``docs/daitum_model/formulas/{NAME}.rst`` whose "Supported types" table is generated from the
   structure-driven metadata derived from the golden drift corpus (not hand-written prose).
3. A new **Operators** page generated from the
   :class:`~daitum_model.expression.OperatorDef` registry (arithmetic, concat, comparison,
   equality, negate, member access, column access) — net-new documentation.

Run this script directly or let ``docs/conf.py`` invoke it during the Sphinx build.
"""

from __future__ import annotations

import importlib
import inspect
import sys
from pathlib import Path

MODULE_NAME = "daitum_model.formulas"
DOCS_DIR = Path(__file__).parent
OUTPUT_DIR = DOCS_DIR / "daitum_model" / "formulas"
INDEX_PATH = DOCS_DIR / "daitum_model" / "formulas.rst"
INTRO_PATH = DOCS_DIR / "daitum_model" / "formulas_intro.rst"
OPERATORS_PATH = DOCS_DIR / "daitum_model" / "operators.rst"


def is_formula_function(obj: object) -> bool:
    return inspect.isfunction(obj) and obj.__name__.isupper() and obj.__name__[0].isalpha()  # type: ignore[union-attr]


def derive_return_types() -> dict[str, list[str]]:
    """Each function's possible **return** types, derived from its ``result_type`` over a complete
    operand pool (one operand per data-type kind, every ``<T>_MAP`` included).

    This is a projection of the real type rule — not a corpus sample — so map/array element types
    are all represented. Delegates to :func:`daitum_model._doc_spec.derive_return_types`, the single
    source shared with the cross-check test. (Accepted *input* types likewise come from the
    declarative per-argument specs via :func:`daitum_model._doc_spec.function_doc_rows`.)
    """
    from daitum_model._doc_spec import derive_return_types as _derive

    return _derive()


def _supported_types_block(title: str, types: list[str]) -> str:
    if not types:
        return ""
    lines = "\n".join(f"   - {t}" for t in types)
    return f"\n**{title}**\n\n.. container:: supported-types\n\n{lines}\n"


def _argument_block(arg: dict) -> str:
    """One named-argument "Accepted types" block, derived from the declarative spec."""
    label = str(arg["name"])
    markers = []
    if arg.get("variadic"):
        markers.append("variadic")
    if arg.get("optional"):
        markers.append("optional")
    if arg.get("literal_only"):
        markers.append("literal")
    suffix = f" ({', '.join(markers)})" if markers else ""
    types = list(arg["accepts"])  # type: ignore[arg-type]
    lines = "\n".join(f"   - {t}" for t in types)
    return (
        f"\n**``{label}``{suffix} — accepted types**\n\n"
        f".. container:: supported-types\n\n{lines}\n"
    )


def _argument_tables(arg_rows: list[dict]) -> str:
    """All per-argument "Accepted types" blocks for a function (empty when it has no operands)."""
    return "".join(_argument_block(arg) for arg in arg_rows)


def main() -> None:
    repo_root = DOCS_DIR.parent
    for pkg_src in [
        repo_root / "daitum-model" / "src",
        repo_root / "daitum-ui" / "src",
        repo_root / "daitum-configuration" / "src",
    ]:
        sys.path.insert(0, str(pkg_src))

    module = importlib.import_module(MODULE_NAME)
    return_types = derive_return_types()

    from daitum_model._doc_spec import function_doc_rows

    arg_rows = function_doc_rows()

    formulas = sorted(
        (name for name, obj in inspect.getmembers(module, is_formula_function)),
    )

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    for name in formulas:
        # Per-argument accepted types from the declarative spec; return types from the corpus.
        type_tables = _argument_tables(arg_rows.get(name, [])) + _supported_types_block(
            "Return types", return_types.get(name, [])
        )
        rst = (
            f"{name}\n{'=' * len(name)}\n\n"
            f".. autofunction:: {MODULE_NAME}.{name}\n"
            f"{type_tables}"
        )
        (OUTPUT_DIR / f"{name}.rst").write_text(rst, encoding="utf-8")

    _write_operators_page()

    intro = INTRO_PATH.read_text(encoding="utf-8")
    toctree = "\n.. toctree::\n   :maxdepth: 1\n   :caption: Formula Reference:\n\n"
    toctree += "\n".join(f"   formulas/{name}" for name in formulas)
    toctree += "\n   operators\n"
    INDEX_PATH.write_text(intro.rstrip() + "\n" + toctree + "\n", encoding="utf-8")
    print(f"Generated {len(formulas)} function stubs, operators page, and {INDEX_PATH}")


def _write_operators_page() -> None:
    from daitum_model._doc_spec import operator_doc_rows

    lines = [
        "Operators",
        "=========",
        "",
        "Daitum operators are first-class expression nodes, documented here alongside the formula",
        "functions. Each renders to a fixed platform expression form and infers its result type",
        "from its operands.",
        "",
    ]
    for row in operator_doc_rows():
        title = f"``{row['symbol']}`` — {row['name']}"
        lines += [
            title,
            "-" * len(title),
            "",
            str(row["doc"]),
            "",
            f"Renders as ``{row['renders']}``.",
            "",
        ]
        lines.append("**Accepted operand types**")
        lines.append("")
        lines.append(".. container:: supported-types")
        lines.append("")
        lines += [f"   - {t}" for t in row["operands"]]  # type: ignore[union-attr]
        lines.append("")
        lines.append("**Result types**")
        lines.append("")
        lines.append(".. container:: supported-types")
        lines.append("")
        lines += [f"   - {t}" for t in row["result"]]  # type: ignore[union-attr]
        lines.append("")
    OPERATORS_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Generated {OPERATORS_PATH}")


if __name__ == "__main__":
    main()
