"""Generate the merged Formulas page and per-formula RST stubs.

The Sphinx page at ``docs/daitum_model/formulas.rst`` is assembled from two
parts:

1. The hand-written intro at ``docs/daitum_model/formulas_intro.rst`` (covers
   the ``Formula`` class, ``CONST``, and a short lead-in).
2. An autogenerated toctree that lists every public formula function in
   :mod:`daitum_model.formulas`. Each function gets its own stub at
   ``docs/daitum_model/formulas/{NAME}.rst``.

Run this script directly or let ``docs/conf.py`` invoke it during the Sphinx
build.
"""

import importlib
import inspect
import sys
from pathlib import Path

MODULE_NAME = "daitum_model.formulas"
DOCS_DIR = Path(__file__).parent
OUTPUT_DIR = DOCS_DIR / "daitum_model" / "formulas"
INDEX_PATH = DOCS_DIR / "daitum_model" / "formulas.rst"
INTRO_PATH = DOCS_DIR / "daitum_model" / "formulas_intro.rst"


def is_formula_function(obj: object) -> bool:
    return inspect.isfunction(obj) and obj.__name__.isupper() and obj.__name__[0].isalpha()  # type: ignore[union-attr]


def main() -> None:
    # Ensure daitum_model is importable when run standalone.
    repo_root = DOCS_DIR.parent
    for pkg_src in [
        repo_root / "daitum-model" / "src",
        repo_root / "daitum-ui" / "src",
        repo_root / "daitum-configuration" / "src",
    ]:
        sys.path.insert(0, str(pkg_src))

    module = importlib.import_module(MODULE_NAME)

    formulas = [(name, obj) for name, obj in inspect.getmembers(module, is_formula_function)]
    formulas.sort(key=lambda x: x[0])

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    for name, _ in formulas:
        rst_path = OUTPUT_DIR / f"{name}.rst"
        rst_path.write_text(
            f"{name}\n{'=' * len(name)}\n\n.. autofunction:: {MODULE_NAME}.{name}\n",
            encoding="utf-8",
        )
        print(f"Generated {rst_path}")

    intro = INTRO_PATH.read_text(encoding="utf-8")
    toctree = "\n.. toctree::\n   :maxdepth: 1\n   :caption: Formula Reference:\n\n"
    toctree += "\n".join(f"   formulas/{name}" for name, _ in formulas)

    INDEX_PATH.write_text(intro.rstrip() + "\n" + toctree + "\n", encoding="utf-8")
    print(f"Generated {INDEX_PATH}")


if __name__ == "__main__":
    main()
